### PR TITLE
Added required libraries

### PR DESCRIPTION
**Pull request by Wingee**

### CODE REVIEW

**Comment by R4mpancy** [comment]
Should we update the gradle build file along with this?

**Comment by m1ga** [comment]
the iid file is part of the ti.playservice module. Currently version 16.0.1 but it should be updated there to 17. Not sure if the other two files should be included there or if they are only used by analytics then they should included here :smile:

**Comment by R4mpancy** [comment]
ahhh that might be the root of the issues I've been having
iid is also used by the cloud messaging module
Even with Wingee's implementation I'm still getting a FCM error

**Comment by hansemannn** [comment]
Using PlayServices 16.1.3 (not 16.1.2 or 16.1.4) fixes the issues without requiring these updates. We could consider moving the libraries to the core though, since they're used by both cloud-messaging and analytics.

**Pull request closed without merging**
